# Add this to:
#   DevPod -> Provider (Kubernetes) -> Advanced Options -> Pod Manifest Template

apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  containers:
    # Do not change this name. It must be "devpod" to change the devpod container.
    - name: devpod
      # image will be defined in devcontainer.json. So changing it here is useless.
      # args will not work.
      # command will not work.
      # environment will not work. You should set environment variables in Dockerfile or devcontainer.json.
      resources: # Change resources as needed.
        requests:
          cpu: "8"
          memory: "32Gi"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
        limits:
          cpu: "16"
          memory: "64Gi"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
      volumeMounts:
        # Host root mount for accessing host files if needed.
        - mountPath: /host
          name: host
          readOnly: true # Avoid accidental changes to host. Set to false if you need write access.
          mountPropagation: HostToContainer # Allows the container to see changes made on the host.
        # Shared memory volume for applications that need it, e.g., inference engines.
        - mountPath: /dev/shm
          name: shm
  volumes:
    # Mount the host's root directory to /host in the pod.
    # This is useful if you want to access files on the host.
    # Be cautious with this as it can pose security risks.
    - name: host
      hostPath:
        path: /
        type: Directory # Make sure it exists.
    # Docker root volume is in emptyDir, implicitly defined in Dockerfile.
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "8Gi" # Adjust size as needed.
