# Add this to:
#   DevPod -> Provider (Kubernetes) -> Advanced Options -> Pod Manifest Template

apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  # Although not required, just to avoid network issues with multi-node RDMA.
  hostNetwork: true
  containers:
    # Do not change this name. It must be "devpod" to change the devpod container.
    - name: devpod
      # image will be defined in devcontainer.json. So changing it here is useless.
      # args will not work.
      # command will not work.
      # environment will not work. You should set environment variables in Dockerfile or devcontainer.json.
      resources: # Change resources as needed.
        requests:
          cpu: "8"
          memory: "32Gi"
          nvidia.com/gpu: "8"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
        limits:
          cpu: "64"
          memory: "256Gi"
          nvidia.com/gpu: "8"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
      volumeMounts:
        # Host root mount for accessing host files if needed.
        - mountPath: /host
          name: host
          readOnly: true # Avoid accidental changes to host. Set to false if you need write access.
  volumes:
    # Mount the host's root directory to /host in the pod.
    # This is useful if you want to access files on the host.
    # Be cautious with this as it can pose security risks.
    - name: host
      hostPath:
        path: /
        type: Directory # Make sure it exists.
    # Docker root volume is in /workspace/docker-root. See docker-daemon.json.
