# Add this to:
#   DevPod -> Provider (Kubernetes) -> Advanced Options -> Pod Manifest Template

# This template is for CPU-only tasks. If you want to use GPUs, use the -nvidia template.

apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  containers:
    # Do not change this name. It must be "devpod" to change the devpod container.
    - name: devpod
      # image will be defined in devcontainer.json. So changing it here is useless.
      # args will not work.
      # command will not work.
      # environment will not work. You should set environment variables in Dockerfile or devcontainer.json.
      resources: # Change resources as needed.
        requests:
          cpu: "8"
          memory: "32Gi"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
        limits:
          cpu: "64"
          memory: "256Gi"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
      volumeMounts:
        # Host root mount for accessing host files if needed.
        - mountPath: /host
          name: host
          readOnly: true # Avoid accidental changes to host. Set to false if you need write access.
        - mountPath: /certs
          name: docker-certs
          readOnly: true
    # Docker daemon sidecar so that Docker-in-Docker works.
    - name: docker
      image: docker:28.3.3-dind-alpine3.22
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      args:
        - --storage-driver=overlay2
      securityContext:
        privileged: true # Required for DinD to work.
        runAsUser: 0
        runAsGroup: 0
      resources: # Change resources as needed.
        requests:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "100Gi"
        limits:
          cpu: "8"
          memory: "16Gi"
          ephemeral-storage: "100Gi" # Avoid filling node disk.
      volumeMounts:
        - mountPath: /certs
          name: docker-certs
          readOnly: false
        - mountPath: /var/lib/docker
          name: docker-root
          readOnly: false
  volumes:
    # Mount the host's root directory to /host in the pod.
    # This is useful if you want to access files on the host.
    # Be cautious with this as it can pose security risks.
    - name: host
      hostPath:
        path: /
        type: Directory # Make sure it exists.
    # Docker client certs volume for Docker-in-Docker.
    - name: docker-certs
      emptyDir:
        medium: Memory
        sizeLimit: 16Mi
    - name: docker-root
      emptyDir:
        medium: ""
        sizeLimit: 80Gi
